- name: Install haproxy and prom-exporter
  apt:
    name:
      - haproxy
      - prometheus-haproxy-exporter

- name: Copy haproxy config file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart haproxy

- name: Alter args in haproxy exporter
  template:
    src: prometheus-haproxy-exporter.j2
    dest: /etc/default/prometheus-haproxy-exporter
  notify: Restart prometheus-haproxy-exporter

- name: Start haproxy and prom-exporter
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - haproxy
    - prometheus-haproxy-exporter

- name: Set CNAME record for haproxy
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_update_key }}"
    server: "{{ item }}"
    zone: "{{ domain }}"
    record: "lb{{ inventory_hostname | replace('porty40', '') }}"
    value: "{{ inventory_hostname }}"
    type: "CNAME"
  with_items: "{{ groups['dns_masters'] }}"
