- name: Add Grafana APT GPG Key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT Repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Install grafana
  apt:
    name: grafana
    state: present

- name: Copy grafana config file
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana

- name: Configure datasources
  template:
    src: datasource.yaml.j2
    dest: /etc/grafana/provisioning/datasources/sample.yaml
  notify: Restart grafana

- name: Configure dashboards directory
  template:
    src: provider.yaml.j2
    dest: /etc/grafana/provisioning/dashboards/sample.yaml
  notify: Restart grafana

- name: Create Grafana Dashboards Directory
  file:
    path: /var/lib/grafana/dashboards
    state: directory

- name: Add dashboards
  copy:
    src: "{{ item }}"
    dest: /var/lib/grafana/dashboards/{{ item }}
  loop:
    - main.json
    - syslog.json
    - mysql.json
  notify: Restart grafana

- name: Start Grafana
  service:
    name: grafana-server
    state: started
    enabled: yes
