{
 "title": "Main",
 "time": { "from": "now-15s", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Load on VMs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1-rate(node_cpu_seconds_total{mode=\"idle\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS Queries per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[1m])"
    }
   ]
  },
  {
   "title": "Bind Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bind_up{job=\"bind\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nginx Requests per Minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{job=\"nginx\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Consumption on VMs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_memory_Active_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT dst, rtt FROM rtt WHERE time >= now() - 1m GROUP BY dst \n"
    }
   ]
  },
  {
   "title": "MYSQL Selects per Minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_commands_total{command=\"select\", instance=\"porty40-2:9104\", job=\"mysql\"}[1m])",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_up{job=\"mysql\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Haproxy Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Influx Write Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(influxdb_write_write_ok{job=\"influx\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived VRRP State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{vrid=\"51\", instance=\"porty40-1:9165\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Keepalived VRRP State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "keepalived_vrrp_state{vrid=\"51\", instance=\"porty40-2:9165\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web_App_Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"porty40-1:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"porty40-2:9101\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}