- name: Install keepalived
  apt:
    name: keepalived

- name: Copy keepalived config
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  no_log: true
  notify: Restart keepalived

- name: Create keepalived_script user
  user:
    name: keepalived_script
    home: /home/keepalived_script

- name: Add vrrp script
  template:
    src: vrrp_script.j2
    dest: /home/keepalived_script/vrrp_script.sh
    owner: keepalived_script
    mode: '0700'
  notify: Restart keepalived

- name: Download keepalived-exporter binary
  get_url:
    url: http://backup/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    dest: /usr/local/bin/keepalived-exporter-1.2.0.linux-amd64.tar.gz

- name: Unarchive binary
  unarchive:
    src: /usr/local/bin/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    owner: root
    mode: '0755'
    remote_src: yes
  notify: Restart keepalived-exporter

- name: Create systemd service unit
  template:
    src: keepalived-exporter.service.j2
    dest: /etc/systemd/system/keepalived-exporter.service
    owner: root
    mode: '0700'
  notify:
    - Reload systemd
    - Restart keepalived-exporter

- name: Start keepalived and keepalived-exporter
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - keepalived
    - keepalived-exporter
