- name: Install prometheus
  apt:
    name: prometheus

- name: Copy prometheus configuration
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'
  notify: Restart prometheus

- name: Alter prometheus arguments
  template:
    src: prometheus.j2
    dest: /etc/default/prometheus
  notify: Restart prometheus

- name: Start prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Set CNAME record for prometheus
  community.general.nsupdate:
    key_name: "nsupdate.key"
    key_algorithm: "hmac-sha256"
    key_secret: "{{ dns_update_key }}"
    server: "{{ item }}"
    zone: "{{ domain }}"
    record: "prometheus"
    value: "{{ inventory_hostname }}"
    type: "CNAME"
  with_items: "{{ groups['dns_masters'] }}"
