- name: Update APT cache
  apt:
    cache_valid_time: 86400

- name: Install prometheus node exporters
  apt:
    name: prometheus-node-exporter

- name: Start node esporters
  service:
    name: prometheus-node-exporter
    state: started
    enabled: yes

- name: Install ca-certificates latest
  apt:
    name: ca-certificates>=20230311ubuntu0.20.04.1

- name: Configure rsyslog for telegraf
  template:
    src: 10-telegraf.conf.j2
    dest: /etc/rsyslog.d/10-telegraf.conf
  notify: Restart rsyslog

- name: Start rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes

- name: Create user 'backup'
  user:
    name: backup
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /home/backup/.ssh/id_rsa
  become: yes

- name: Add backup server to known hosts
  template:
    src: backup_host.j2
    dest: /home/backup/.ssh/known_hosts
    owner: backup
    group: backup
    mode: '0700'

- name: Add /home/backup/restore directory for backup
  file:
    path: /home/backup/restore
    state: directory
    owner: backup
    mode: '0700'

- name: Install duplicity
  apt:
    name: duplicity
